apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "test-nodejs.fullname" . }}
spec:
  gateways:
  - {{ include "test-nodejs.fullname" . }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix:  {{ .Values.virtualService.prefix }}
    route:
    - destination:
        host: {{ include "test-nodejs.fullname" . }}
        port:
          number: {{ .Values.service.port }}